# Generated by Django 4.2.3 on 2023-12-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifter',
            name='nickname',
            field=models.TextField(blank=True),
        ),
    ]
