# Generated by Django 4.2.3 on 2023-12-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0002_shifter_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/<username>/'),
        ),
    ]
