# Generated by Django 4.2.3 on 2023-12-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0003_alter_shifter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
